# Generated by Django 3.2.22 on 2023-10-25 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AñoEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AñoInicio', models.DateField(db_column='año_inicio')),
                ('Añofinal', models.DateField(db_column='año_final')),
                ('actual', models.BooleanField()),
            ],
            options={
                'db_table': 'año_escolar',
            },
        ),
        migrations.CreateModel(
            name='AñoEscolarizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'año_escolarizacion',
            },
        ),
        migrations.CreateModel(
            name='AñoEscolarizacionSeccionesAñoEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.añoescolarizacion')),
                ('añoEscolar', models.ForeignKey(db_column='año_escolar_id', on_delete=django.db.models.deletion.CASCADE, to='API.añoescolar')),
            ],
            options={
                'db_table': 'año_escolarizacion_has_secciones_año_escolar',
            },
        ),
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'cargos',
            },
        ),
        migrations.CreateModel(
            name='EstadosEstudiantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'estado_estudiante',
            },
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugarNacimiento', models.CharField(db_column='lugar_nacimiento', max_length=100)),
                ('direccion', models.CharField(db_column='direccion_habitacional', max_length=250)),
                ('procedencia', models.CharField(db_column='plandel_procedencia', max_length=100)),
                ('observaciones', models.CharField(blank=True, max_length=1000, null=True)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, db_column='fecha_registro')),
                ('fechaActualizacion', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('añoIngreso', models.ForeignKey(db_column='año_ingreso_id', on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='API.añoescolarizacion')),
                ('estado', models.ForeignKey(db_column='estado_id', on_delete=django.db.models.deletion.CASCADE, to='API.estadosestudiantee')),
            ],
            options={
                'db_table': 'estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'generos',
            },
        ),
        migrations.CreateModel(
            name='Inscripciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, db_column='fecha_registro')),
                ('fechaActualizacion', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('aprobado', models.BooleanField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, related_name='inscripcion', to='API.estudiantes')),
            ],
            options={
                'db_table': 'inscripciones',
            },
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligatoria', models.BooleanField(default=True)),
                ('tipoNota', models.BooleanField(db_column='tipo_nota', default=True)),
                ('año', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.añoescolarizacion')),
            ],
            options={
                'db_table': 'Materias',
            },
        ),
        migrations.CreateModel(
            name='NombreMaterias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'Nombres_Materias',
            },
        ),
        migrations.CreateModel(
            name='Parentescos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'parentescos',
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nacionalidad', models.BooleanField()),
                ('cedula', models.BigIntegerField(unique=True)),
                ('propia', models.BooleanField(default=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.BigIntegerField()),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, db_column='fecha_registro')),
                ('fechaActualizacion', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('genero', models.ForeignKey(db_column='genero_id', on_delete=django.db.models.deletion.CASCADE, related_name='persona', to='API.generos')),
            ],
            options={
                'db_table': 'personas',
            },
        ),
        migrations.CreateModel(
            name='Secciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'db_table': 'secciones',
            },
        ),
        migrations.CreateModel(
            name='TipoInscripciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'tipo_inscripciones',
            },
        ),
        migrations.CreateModel(
            name='Requisitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificadoNotas', models.BooleanField(db_column='certificado_notas')),
                ('boletaPromocion', models.BooleanField(db_column='boleta_promocion')),
                ('cartaConducta', models.BooleanField(db_column='carta_buena_conducta')),
                ('fotosEstudiante', models.BooleanField(db_column='fotos_estudiante')),
                ('fotosRepresentante', models.BooleanField(db_column='fotos_representante')),
                ('fotocopiaCedulaEstudiante', models.BooleanField(db_column='fotocopia_cedula_estudiante')),
                ('fotocopiaCedulaRepresentante', models.BooleanField(db_column='fotocopia_cedula_representante')),
                ('partidaNacimiento', models.BooleanField(db_column='partida_nacimiento')),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, db_column='fecha_registro')),
                ('fechaActualizacion', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('estudiante', models.OneToOneField(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='API.estudiantes')),
            ],
            options={
                'db_table': 'requisitos',
            },
        ),
        migrations.CreateModel(
            name='Representantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('fallecido', models.BooleanField(default=False)),
                ('profesion', models.CharField(default='Ninguna', max_length=200)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, db_column='fecha_registro')),
                ('fechaActualizacion', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('persona', models.OneToOneField(db_column='persona_id', on_delete=django.db.models.deletion.CASCADE, related_name='representante', to='API.personas')),
            ],
            options={
                'db_table': 'representantes',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20, unique=True)),
                ('constraseña', models.CharField(max_length=500)),
                ('inhabilitado', models.BooleanField(default=False)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, db_column='fecha_registro')),
                ('fechaActualizacion', models.DateTimeField(auto_now=True, db_column='fecha_actualizacion')),
                ('cargo', models.ForeignKey(db_column='cargo_id', on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='API.cargos')),
                ('persona', models.OneToOneField(db_column='persona_id', on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='API.personas')),
            ],
            options={
                'db_table': 'personal',
            },
        ),
        migrations.CreateModel(
            name='NotasMaterias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('estudiante', models.ForeignKey(db_column='estudiante_id', on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='API.estudiantes')),
                ('materia', models.ForeignKey(db_column='materia_id', on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='API.materias')),
            ],
            options={
                'db_table': 'notas_materias',
            },
        ),
        migrations.CreateModel(
            name='MateriasInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(default=0)),
                ('inscripcion', models.ForeignKey(db_column='inscripcion_id', on_delete=django.db.models.deletion.CASCADE, related_name='matrias_inscripcion', to='API.inscripciones')),
                ('materia', models.ForeignKey(db_column='materia_id', on_delete=django.db.models.deletion.CASCADE, related_name='matrias_inscripcion', to='API.materias')),
            ],
            options={
                'db_table': 'materias_has_inscripcion',
            },
        ),
        migrations.AddField(
            model_name='materias',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.nombrematerias'),
        ),
        migrations.AddField(
            model_name='inscripciones',
            name='parentesco',
            field=models.ForeignKey(db_column='parentesco_id', on_delete=django.db.models.deletion.CASCADE, related_name='inscripcion', to='API.parentescos'),
        ),
        migrations.AddField(
            model_name='inscripciones',
            name='representanteLegal',
            field=models.ForeignKey(db_column='representante_legal_id', on_delete=django.db.models.deletion.CASCADE, related_name='inscripcion', to='API.representantes'),
        ),
        migrations.AddField(
            model_name='inscripciones',
            name='respondable',
            field=models.ForeignKey(db_column='respondable_id', on_delete=django.db.models.deletion.CASCADE, related_name='inscripcion', to='API.personal'),
        ),
        migrations.AddField(
            model_name='inscripciones',
            name='seccionAño',
            field=models.ForeignKey(db_column='seccion_año_id', on_delete=django.db.models.deletion.CASCADE, related_name='inscripcion', to='API.añoescolarizacionseccionesañoescolar'),
        ),
        migrations.AddField(
            model_name='inscripciones',
            name='tipoInscripcion',
            field=models.ForeignKey(db_column='tipo_inscripcion_id', on_delete=django.db.models.deletion.CASCADE, related_name='inscripcion', to='API.tipoinscripciones'),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='persona',
            field=models.OneToOneField(db_column='persona_id', on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='API.personas'),
        ),
        migrations.AddField(
            model_name='añoescolarizacionseccionesañoescolar',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.secciones'),
        ),
    ]
