# Generated by Django 3.2.22 on 2023-10-25 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_representantes_profesion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='constraseña',
            new_name='contraseña',
        ),
    ]
