# Generated by Django 3.2.22 on 2023-10-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_rename_constraseña_personal_contraseña'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personas',
            name='nombre',
        ),
        migrations.AddField(
            model_name='personas',
            name='apellidos',
            field=models.CharField(default='Medina Nazareth', max_length=100),
        ),
        migrations.AddField(
            model_name='personas',
            name='nombres',
            field=models.CharField(default='Pedro Medina', max_length=100),
        ),
    ]
