# Generated by Django 3.2.22 on 2023-10-29 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20231027_0359'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='representanteestudiante',
            table='representantes_has_estudiantes',
        ),
    ]
